$('.owl-carousel').owlCarousel({
    loop:false,
    margin:0,
    nav:false,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        750:{
            items:2
        },
        1000:{
            items:2
        },
        1100:{
            items:3
        }
    }
})